[package]
name = "fasterapi"
version = "0.1.0"
edition = "2024"

[dependencies]
once_cell = "1.21.3"
pyo3 = { version = "0.26.0", features = ["extension-module"] }

[lib]
name = "fasterapi"
crate-type = ["cdylib"]  # important for Python