#[macro_export]
macro_rules! generate_http_methods {
    ($struct_name:ident, $get_router:ident) => {
        #[pyo3::prelude::pymethods]
        impl $struct_name {
            #[pyo3(signature = (path, *, response_model=None, status_code=None, tags=None, dependencies=None, summary=None, description=None, response_description=None, responses=None, deprecated=None, operation_id=None, response_model_include=None, response_model_exclude=None, response_model_by_alias=true, response_model_exclude_unset=false, response_model_exclude_defaults=false, response_model_exclude_none=false, include_in_schema=true, response_class=None, name=None, callbacks=None, openapi_extra=None, generate_unique_id_function=None, cache_resp=false, rate_limit=None))]
            #[allow(unused_variables)]
            fn get(&self, py: pyo3::prelude::Python<'_>, path: String, response_model: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, status_code: Option<u16>, tags: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, dependencies: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, summary: Option<String>, description: Option<String>, response_description: Option<String>, responses: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, deprecated: Option<bool>, operation_id: Option<String>, response_model_include: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, response_model_exclude: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, response_model_by_alias: bool, response_model_exclude_unset: bool, response_model_exclude_defaults: bool, response_model_exclude_none: bool, include_in_schema: bool, response_class: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, name: Option<String>, callbacks: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, openapi_extra: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, generate_unique_id_function: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, cache_resp: bool, rate_limit: Option<u32>) -> pyo3::prelude::PyResult<pyo3::prelude::Py<pyo3::prelude::PyAny>> {
                self.$get_router(py).create_method_decorator(py, crate::routing::types::HttpMethod::GET, path, status_code, response_model.clone(), response_class.clone(), tags, summary, description, deprecated, include_in_schema, cache_resp, rate_limit)
            }
            #[pyo3(signature = (path, *, response_model=None, status_code=None, tags=None, dependencies=None, summary=None, description=None, response_description=None, responses=None, deprecated=None, operation_id=None, response_model_include=None, response_model_exclude=None, response_model_by_alias=true, response_model_exclude_unset=false, response_model_exclude_defaults=false, response_model_exclude_none=false, include_in_schema=true, response_class=None, name=None, callbacks=None, openapi_extra=None, generate_unique_id_function=None, cache_resp=false, rate_limit=None))]
            #[allow(unused_variables)]
            fn post(&self, py: pyo3::prelude::Python<'_>, path: String, response_model: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, status_code: Option<u16>, tags: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, dependencies: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, summary: Option<String>, description: Option<String>, response_description: Option<String>, responses: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, deprecated: Option<bool>, operation_id: Option<String>, response_model_include: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, response_model_exclude: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, response_model_by_alias: bool, response_model_exclude_unset: bool, response_model_exclude_defaults: bool, response_model_exclude_none: bool, include_in_schema: bool, response_class: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, name: Option<String>, callbacks: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, openapi_extra: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, generate_unique_id_function: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, cache_resp: bool, rate_limit: Option<u32>) -> pyo3::prelude::PyResult<pyo3::prelude::Py<pyo3::prelude::PyAny>> {
                self.$get_router(py).create_method_decorator(py, crate::routing::types::HttpMethod::POST, path, status_code, response_model.clone(), response_class.clone(), tags, summary, description, deprecated, include_in_schema, cache_resp, rate_limit)
            }
            #[pyo3(signature = (path, *, response_model=None, status_code=None, tags=None, dependencies=None, summary=None, description=None, response_description=None, responses=None, deprecated=None, operation_id=None, response_model_include=None, response_model_exclude=None, response_model_by_alias=true, response_model_exclude_unset=false, response_model_exclude_defaults=false, response_model_exclude_none=false, include_in_schema=true, response_class=None, name=None, callbacks=None, openapi_extra=None, generate_unique_id_function=None, cache_resp=false, rate_limit=None))]
            #[allow(unused_variables)]
            fn put(&self, py: pyo3::prelude::Python<'_>, path: String, response_model: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, status_code: Option<u16>, tags: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, dependencies: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, summary: Option<String>, description: Option<String>, response_description: Option<String>, responses: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, deprecated: Option<bool>, operation_id: Option<String>, response_model_include: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, response_model_exclude: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, response_model_by_alias: bool, response_model_exclude_unset: bool, response_model_exclude_defaults: bool, response_model_exclude_none: bool, include_in_schema: bool, response_class: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, name: Option<String>, callbacks: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, openapi_extra: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, generate_unique_id_function: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, cache_resp: bool, rate_limit: Option<u32>) -> pyo3::prelude::PyResult<pyo3::prelude::Py<pyo3::prelude::PyAny>> {
                self.$get_router(py).create_method_decorator(py, crate::routing::types::HttpMethod::PUT, path, status_code, response_model.clone(), response_class.clone(), tags, summary, description, deprecated, include_in_schema, cache_resp, rate_limit)
            }
            #[pyo3(signature = (path, *, response_model=None, status_code=None, tags=None, dependencies=None, summary=None, description=None, response_description=None, responses=None, deprecated=None, operation_id=None, response_model_include=None, response_model_exclude=None, response_model_by_alias=true, response_model_exclude_unset=false, response_model_exclude_defaults=false, response_model_exclude_none=false, include_in_schema=true, response_class=None, name=None, callbacks=None, openapi_extra=None, generate_unique_id_function=None, cache_resp=false, rate_limit=None))]
            #[allow(unused_variables)]
            fn delete(&self, py: pyo3::prelude::Python<'_>, path: String, response_model: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, status_code: Option<u16>, tags: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, dependencies: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, summary: Option<String>, description: Option<String>, response_description: Option<String>, responses: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, deprecated: Option<bool>, operation_id: Option<String>, response_model_include: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, response_model_exclude: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, response_model_by_alias: bool, response_model_exclude_unset: bool, response_model_exclude_defaults: bool, response_model_exclude_none: bool, include_in_schema: bool, response_class: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, name: Option<String>, callbacks: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, openapi_extra: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, generate_unique_id_function: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, cache_resp: bool, rate_limit: Option<u32>) -> pyo3::prelude::PyResult<pyo3::prelude::Py<pyo3::prelude::PyAny>> {
                self.$get_router(py).create_method_decorator(py, crate::routing::types::HttpMethod::DELETE, path, status_code, response_model.clone(), response_class.clone(), tags, summary, description, deprecated, include_in_schema, cache_resp, rate_limit)
            }
            #[pyo3(signature = (path, *, response_model=None, status_code=None, tags=None, dependencies=None, summary=None, description=None, response_description=None, responses=None, deprecated=None, operation_id=None, response_model_include=None, response_model_exclude=None, response_model_by_alias=true, response_model_exclude_unset=false, response_model_exclude_defaults=false, response_model_exclude_none=false, include_in_schema=true, response_class=None, name=None, callbacks=None, openapi_extra=None, generate_unique_id_function=None, cache_resp=false, rate_limit=None))]
            #[allow(unused_variables)]
            fn patch(&self, py: pyo3::prelude::Python<'_>, path: String, response_model: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, status_code: Option<u16>, tags: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, dependencies: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, summary: Option<String>, description: Option<String>, response_description: Option<String>, responses: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, deprecated: Option<bool>, operation_id: Option<String>, response_model_include: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, response_model_exclude: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, response_model_by_alias: bool, response_model_exclude_unset: bool, response_model_exclude_defaults: bool, response_model_exclude_none: bool, include_in_schema: bool, response_class: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, name: Option<String>, callbacks: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, openapi_extra: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, generate_unique_id_function: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, cache_resp: bool, rate_limit: Option<u32>) -> pyo3::prelude::PyResult<pyo3::prelude::Py<pyo3::prelude::PyAny>> {
                self.$get_router(py).create_method_decorator(py, crate::routing::types::HttpMethod::PATCH, path, status_code, response_model.clone(), response_class.clone(), tags, summary, description, deprecated, include_in_schema, cache_resp, rate_limit)
            }
            #[pyo3(signature = (path, *, response_model=None, status_code=None, tags=None, dependencies=None, summary=None, description=None, response_description=None, responses=None, deprecated=None, operation_id=None, response_model_include=None, response_model_exclude=None, response_model_by_alias=true, response_model_exclude_unset=false, response_model_exclude_defaults=false, response_model_exclude_none=false, include_in_schema=true, response_class=None, name=None, callbacks=None, openapi_extra=None, generate_unique_id_function=None, cache_resp=false, rate_limit=None))]
            #[allow(unused_variables)]
            fn options(&self, py: pyo3::prelude::Python<'_>, path: String, response_model: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, status_code: Option<u16>, tags: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, dependencies: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, summary: Option<String>, description: Option<String>, response_description: Option<String>, responses: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, deprecated: Option<bool>, operation_id: Option<String>, response_model_include: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, response_model_exclude: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, response_model_by_alias: bool, response_model_exclude_unset: bool, response_model_exclude_defaults: bool, response_model_exclude_none: bool, include_in_schema: bool, response_class: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, name: Option<String>, callbacks: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, openapi_extra: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, generate_unique_id_function: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, cache_resp: bool, rate_limit: Option<u32>) -> pyo3::prelude::PyResult<pyo3::prelude::Py<pyo3::prelude::PyAny>> {
                self.$get_router(py).create_method_decorator(py, crate::routing::types::HttpMethod::OPTIONS, path, status_code, response_model.clone(), response_class.clone(), tags, summary, description, deprecated, include_in_schema, cache_resp, rate_limit)
            }
            #[pyo3(signature = (path, *, response_model=None, status_code=None, tags=None, dependencies=None, summary=None, description=None, response_description=None, responses=None, deprecated=None, operation_id=None, response_model_include=None, response_model_exclude=None, response_model_by_alias=true, response_model_exclude_unset=false, response_model_exclude_defaults=false, response_model_exclude_none=false, include_in_schema=true, response_class=None, name=None, callbacks=None, openapi_extra=None, generate_unique_id_function=None, cache_resp=false, rate_limit=None))]
            #[allow(unused_variables)]
            fn head(&self, py: pyo3::prelude::Python<'_>, path: String, response_model: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, status_code: Option<u16>, tags: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, dependencies: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, summary: Option<String>, description: Option<String>, response_description: Option<String>, responses: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, deprecated: Option<bool>, operation_id: Option<String>, response_model_include: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, response_model_exclude: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, response_model_by_alias: bool, response_model_exclude_unset: bool, response_model_exclude_defaults: bool, response_model_exclude_none: bool, include_in_schema: bool, response_class: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, name: Option<String>, callbacks: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, openapi_extra: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, generate_unique_id_function: Option<pyo3::prelude::Py<pyo3::prelude::PyAny>>, cache_resp: bool, rate_limit: Option<u32>) -> pyo3::prelude::PyResult<pyo3::prelude::Py<pyo3::prelude::PyAny>> {
                self.$get_router(py).create_method_decorator(py, crate::routing::types::HttpMethod::HEAD, path, status_code, response_model.clone(), response_class.clone(), tags, summary, description, deprecated, include_in_schema, cache_resp, rate_limit)
            }
        }
    }
}
