name: Maturin Build + PGO + Publish (multi-platform abi3)

on:
  push:
    tags:
      - 'v*'  # publish to PyPI when version tags are pushed
  workflow_dispatch:  # manual trigger → publish to TestPyPI

permissions:
  contents: write
  id-token: write

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    env:
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: full

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9 (for abi3)
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Prepare profiling directory
        shell: bash
        run: mkdir -p ${{ github.workspace }}/profdata

      - name: Build instrumented wheel (profile-generate)
        uses: PyO3/maturin-action@v1
        with:
          manylinux: auto
          args: >
            --release
            --out pgo-wheel
            --interpreter python3.9
          rust-toolchain: stable
        env:
          RUSTFLAGS: '-Cprofile-generate=${{ github.workspace }}/profdata'

      # Detect llvm-profdata properly on all platforms
      - name: Detect LLVM profdata tool
        id: detect-profdata
        run: |
          rust_host=$(rustc -Vv | grep host | awk '{print $2}')
          toolchain=$(rustup show active-toolchain | cut -d ' ' -f 1)
          sysroot=$(rustc --print sysroot)
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            echo "LLVM_PROFDATA=$(cygpath -w "$sysroot\\lib\\rustlib\\$rust_host\\bin\\llvm-profdata.exe")" >> "$GITHUB_ENV"
          else
            echo "LLVM_PROFDATA=$sysroot/lib/rustlib/$rust_host/bin/llvm-profdata" >> "$GITHUB_ENV"
          fi
        shell: bash

      # Merge profiling data with OS-specific shells
      - name: Merge PGO data (Linux/Mac)
        if: runner.os != 'Windows'
        shell: bash
        run: ${{ env.LLVM_PROFDATA }} merge -o merged.profdata profdata

      - name: Merge PGO data (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          & "${{ env.LLVM_PROFDATA }}" merge -o merged.profdata profdata

      - name: Build PGO-optimized abi3 wheel
        uses: PyO3/maturin-action@v1
        with:
          manylinux: auto
          args: >
            --release
            --out dist
            --interpreter python3.9
          rust-toolchain: stable
        env:
          RUSTFLAGS: '-Cprofile-use=${{ github.workspace }}/merged.profdata'

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: abi3-pgo-${{ matrix.os }}
          path: dist/*.whl

  publish:
    name: Publish to PyPI or TestPyPI
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: write
      attestations: write

    steps:
      - name: Download all built artifacts
        uses: actions/download-artifact@v4
        with:
          path: wheels

      - name: Show collected wheels
        run: ls -R wheels

      - name: Publish to PyPI (tagged release)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
